import type { Metadata } from "next";
import {Encode_Sans_Expanded } from "next/font/google";
import "./globals.css";
import { Navbar } from "./(main)/_components/Navbar/Navbar";
import Footer from "./(main)/_components/Footer/Footer";
import '@fortawesome/fontawesome-free/css/all.css'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Toaster } from "@/components/ui/sonner"
import UserSession from "@/UserSession";
import CountProvider from "./countProvider";
import 'flowbite';


const Encode_Sans_ExpandedFont = Encode_Sans_Expanded({
  weight : ["100" ,"400" , "800"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Encode_Sans_ExpandedFont.className}>

     <UserSession>
     <CountProvider>

       <Navbar/>
      <div className="p-5">
        
        {children}

          <Toaster />

      </div>
      <div>
        <Footer/>
      </div>


     </CountProvider>
     </UserSession>
       
      </body>
    </html>
  );
}
